"""NVIDIA Dynamo v1.0+ engine adapter and config compiler."""

from __future__ import annotations

from typing import Any

from inferscope.engines.base import (
    ConfigCompiler,
    DeploymentInventory,
    EngineAdapter,
    EngineConfig,
)
from inferscope.optimization.serving_profile import ServingProfile


class DynamoCompiler(ConfigCompiler):
    """Compiles a ServingProfile into Dynamo config."""

    def engine_name(self) -> str:
        return "dynamo"

    def compile(self, profile: ServingProfile, inventory: DeploymentInventory) -> EngineConfig:
        cfg = EngineConfig(engine="dynamo")
        cfg.notes.append("Dynamo 1.0 uses declarative YAML config (generated by launcher)")
        cfg.notes.append("Components enabled: SLO Planner, KV-aware Router, NIXL, Grove")

        cfg.cli_flags["config"] = "/tmp/dynamo-config.yaml"  # noqa: S108

        if profile.topology.split_prefill_decode and not inventory.has_rdma:
            cfg.warnings.append(
                "CRITICAL: Disaggregated serving without RDMA causes severe bottleneck. "
                "Either enable RDMA or disable prefill/decode splitting."
            )

        cmd_parts = ["dynamo", "serve"]
        for k, v in cfg.cli_flags.items():
            if isinstance(v, bool):
                if v:
                    cmd_parts.append(f"--{k}")
            else:
                cmd_parts.append(f"--{k}")
                cmd_parts.append(str(v))
        cfg.command = " \\\n  ".join(cmd_parts)

        return cfg


class DynamoAdapter(EngineAdapter):
    """Dynamo engine adapter."""

    def engine_name(self) -> str:
        return "dynamo"

    async def detect_engine(self, endpoint: str) -> bool:
        return False  # Phase 5

    async def get_metrics(self, endpoint: str) -> dict[str, Any]:
        return {}

    async def get_config(self, endpoint: str) -> dict[str, Any]:
        return {}
