"""NVIDIA Dynamo v1.0+ engine adapter and config compiler."""

from __future__ import annotations

from typing import Any

from inferscope.engines.base import (
    ConfigCompiler,
    DeploymentInventory,
    EngineAdapter,
    EngineConfig,
)
from inferscope.optimization.serving_profile import ServingProfile


class DynamoCompiler(ConfigCompiler):
    """Compiles a ServingProfile into Dynamo config."""

    def engine_name(self) -> str:
        return "dynamo"

    def compile(self, profile: ServingProfile, inventory: DeploymentInventory) -> EngineConfig:
        cfg = EngineConfig(engine="dynamo")
        cfg.support_tier = "supported"
        cfg.support_reason = (
            "Dynamo 1.0 is a production orchestration layer for NVIDIA disaggregated serving "
            "with KV-aware routing, NIXL transfer, and SLO-driven autoscaling."
        )
        cfg.notes.append("Dynamo 1.0 uses declarative YAML config (generated by launcher)")
        cfg.notes.append("Components: Smart Router, SLO Planner, KV Block Manager, NIXL")
        cfg.notes.append("Worker engines: vLLM, SGLang, or TensorRT-LLM backends")

        cfg.cli_flags["config"] = "configs/dynamo-config.yaml"

        if profile.topology.split_prefill_decode and not inventory.has_rdma:
            cfg.warnings.append(
                "CRITICAL: Disaggregated serving without RDMA causes severe bottleneck. "
                "Either enable RDMA or disable prefill/decode splitting."
            )

        cmd_parts = ["dynamo", "serve"]
        for k, v in cfg.cli_flags.items():
            if isinstance(v, bool):
                if v:
                    cmd_parts.append(f"--{k}")
            else:
                cmd_parts.append(f"--{k}")
                cmd_parts.append(str(v))
        cfg.command = " \\\n  ".join(cmd_parts)

        return cfg


_DYNAMO_METRIC_PREFIXES = (
    "dynamo_component_router_",
    "dynamo_router_overhead_",
    "dynamo_frontend_worker_",
)


class DynamoAdapter(EngineAdapter):
    """Dynamo engine adapter — detects running Dynamo routers via Prometheus metrics."""

    def engine_name(self) -> str:
        return "dynamo"

    async def detect_engine(self, endpoint: str) -> bool:
        """Detect a running Dynamo router by checking for Dynamo metric prefixes."""
        from inferscope.telemetry.prometheus import scrape_metrics

        try:
            scrape = await scrape_metrics(endpoint, allow_private=True)
        except Exception:  # noqa: BLE001
            return False
        if scrape.error:
            return False
        return scrape.engine == "dynamo"

    async def get_metrics(self, endpoint: str) -> dict[str, Any]:
        """Scrape and return Dynamo-family metrics with label dimensions preserved."""
        from inferscope.telemetry.prometheus import scrape_metrics

        try:
            scrape = await scrape_metrics(endpoint, allow_private=True)
        except Exception:  # noqa: BLE001
            return {}
        if scrape.error:
            return {}

        result: dict[str, Any] = {}
        for sample in scrape.samples:
            if any(sample.name.startswith(p) for p in _DYNAMO_METRIC_PREFIXES):
                if sample.labels:
                    # Canonical key with sorted labels for deterministic output
                    label_parts = ",".join(
                        f'{k}="{v}"' for k, v in sorted(sample.labels.items())
                    )
                    key = f"{sample.name}{{{label_parts}}}"
                else:
                    key = sample.name
                result[key] = sample.value
        return result

    async def get_config(
        self,
        endpoint: str,
        *,
        allow_private: bool = True,
        auth: Any = None,
    ) -> dict[str, Any]:
        """Dynamo config introspection — not yet available from upstream API."""
        return {"available": False, "reason": "no_supported_admin_api"}
